services:

  # DB Service
  postgres:
    container_name: pagamento-simplificado-postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - pagamento-simplificado-network

  # App service
  pagamento-simplificado:
    container_name: pagamento-simplificado-app
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - pagamento-simplificado-network

networks:
  pagamento-simplificado-network: