services:

  # DB Service
  postgresql:
    container_name: postgresql
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pagamento-simplificado-network

  # App service
  pagamento-simplificado:
    container_name: pagamento-simplificado-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - pagamento-simplificado-network

networks:
  pagamento-simplificado-network:
    driver: bridge
